### PR TITLE
chore: add mobile menu close, rename navLinks

### PR DESCRIPTION
**Pull request by mikecebul**
I made the mobile nav menu close when a link was selected for issue #26. The fix was simple by creating a function that sets the state that can be passed down to the child component (main-nav -> mobile-nav). By creating a new prop it made sense to make the items more descriptive to what they really are. 

This still leaves the issue of not being able to apply a close animation. The tailwindcss-animate requires a transition component to handle this as shown in their [issues](https://github.com/jamiebuilds/tailwindcss-animate/issues/9). I would do this easily with headlessUI, but it seems like shadcn would prefer to stick with radix. The Radix documentation suggests useTransistion from ['react-spring'](https://react-spring.dev/hooks/use-transition#usetransition/). If we're going to do that, then we should probably just use Radix's [Navigation Menu primitive](https://www.radix-ui.com/docs/primitives/components/navigation-menu).

Let me know which direction you want to go.

This is my first ever pull request and I didn't know if I should name the commit chore or feat. Hopefully you can give me some feedback to improve future pull requests.

### CODE REVIEW

**Comment by shadcn** [comment]
@mikecebul Thanks for the PR. This is looking good. Man I wish my first PR was as good as this :)

I tried to deploy this but seeing a type error.

```ts
Type error: Type '{ items: NavItem[]; }' is not assignable to type 'IntrinsicAttributes & MainNavProps'.
```

Does this build for you locally?

**Comment by mikecebul** [comment]
I updated the naming convention in docs and dashboard to remove the errors. I now realize this is more of an opinionated change and I probably should of just left the naming convention alone. 

I can't do a full build because it fails with 
```
Error: Failed to collect page data for /dashboard/settings
```
I'm guessing because I don't have the env variables.

**Comment by mikecebul** [comment]
I was digging into the RadixUI docs last night. I'm pretty sure I can get the Navigation Menu Primitive implemented in here too.. That will be the next think I'll work on.

**Comment by mikecebul** [comment]
I found it impossible to pass a function to the docs navigation with the component passed as {children}. I decided to make the docs mobile navigation component a conditional in the Main Nav based on the path segment using useSelectedLayoutSegment(). Here's the code section.
```
{showMobileMenu && (
        <MobileNav items={items} handleShowMobileMenu={handleShowMobileMenu}>
          {segment === "docs" ? (
            <DocsSidebarNav
              items={docsConfig.sidebarNav}
              handleShowMobileMenu={handleShowMobileMenu}
            />
          ) : (
            children
          )}
        </MobileNav>
      )}
```
Also I revert the naming convention change of the props "Items" (I changed my mind).

This seems to allow 'close on click' with the least change in the code and without useContext or other providers.

**Pull request closed without merging**
